# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 
email: contact@techblog.local
description: >- # this means to ignore newlines until "baseurl:"
  Comprehensive guides and tutorials for modern development tools, frameworks, 
  and system administration. Featuring in-depth articles on Frappe-Bench, 
  Jekyll, Linux distributions, and development workflows.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: techblog
github_username: techblog
# near the top of _config.yml
repository: https://github.com/inxeoz/docs_frappe.git

# Build settings
# theme: minima
theme: just-the-docs

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  docs:
    output: true
    permalink: /docs/:path/
    


defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: docs

# highlighter (optional)
highlighter: rouge


# just-the-docs options (basic)
just_the_docs:
  # show the site title in the sidebar header
  show_sidebar: true
  # enable search
  search_enabled: true
