name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # - name: Set up Ruby and Bundler cache
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.1'        # change if you need a different Ruby
      #     bundler-cache: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2 # Update to 3.2.0 or higher          

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Build the site with Jekyll
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --destination ./_site

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          keep_files: false
